- Cargo.lock
- Cargo.toml
- README.md
- Rocket.toml
- src/android/mod.rs
- src/config.rs
- src/dirs.rs
- src/endpoints/mod.rs
- src/lib.rs
- src/main.rs
- tests/api.rs
Need to think a few more things through to make it work in a nice manner
> WIP: Create config

- .gitignore
- Cargo.toml
- compile-android.sh
- scripts/create-cargo-config.sh
- src/android/mod.rs
- src/config.rs
- src/datastore/datastore.rs
- src/dirs.rs
- src/endpoints/bucket.rs
- src/endpoints/export.rs
- src/endpoints/import.rs
- src/endpoints/mod.rs
- src/endpoints/query.rs
- src/lib.rs
- src/logging.rs
- src/main.rs
- src/models/bucket.rs
- src/models/event.rs
- src/models/query.rs
- src/query/functions.rs
- src/query/mod.rs
- src/transform/mod.rs
- tests/api.rs
Read all about it here: https://doc.rust-lang.org/edition-guide/rust-2018/index.html
> Switched to Rust Edition 2018 (`cargo fix --edition` + manual fixes)

- Cargo.lock
- Cargo.toml
- src/android/mod.rs
- src/config.rs
- src/endpoints/cors.rs
- src/endpoints/mod.rs
- src/main.rs
- tests/api.rs
Will resolve #24 
Uses the rocket_cors 0.5.1-beta-1 discussed about here
https://github.com/lawliet89/rocket_cors/issues/31
> Use safe CORS configuration

- Cargo.toml
I need this to be able to properly debug stuff in aw-android.
> Added debug symbols to release builds

- compile-android.sh
- src/config.rs
- src/datastore/datastore.rs
- src/endpoints/bucket.rs
Fixes https://github.com/ActivityWatch/aw-android/issues/25
> Bucket default data fix

- src/endpoints/cors.rs
> endpoints: make cors allow all moz-extensions

- Cargo.lock
- Cargo.toml
> Dependency update

- src/datastore/datastore.rs
- tests/datastore.rs
> datastore: Fix bucket.created becoming 1970 if not specified

- src/endpoints/mod.rs
webui is currently broken with the latest master, this fixes that
> endpoints: Update aw-webui and fix endpoints accordingly

- Cargo.lock
- aw-datastore/Cargo.toml
- aw-datastore/src/worker.rs
- aw-query/src/datatype.rs
- aw-query/tests/query.rs
- aw-transform/src/classify.rs
- Fixed lots of unwraps
- Added "ignore_case" support for RegexRule
- Added Rule::None
- Added proper checking of rule type (no longer assumes regex type)
> Rule fixes

- Cargo.lock
- aw-client-rust/src/lib.rs
- aw-client-rust/tests/test.rs
- aw-datastore/src/datastore.rs
- aw-datastore/src/worker.rs
- aw-datastore/tests/datastore.rs
- aw-server/src/endpoints/bucket.rs
- aw-server/src/endpoints/mod.rs
- aw-server/tests/api.rs
> Add support for deleting events

- aw-query/src/datatype.rs
- aw-query/tests/query.rs
Fixes "Show category" button in aw-webui
> aw-query: Fix parsing of lists

- aw-query/src/functions.rs
- aw-query/src/parser.rs
- aw-query/tests/query.rs
- aw-transform/src/find_bucket.rs
- aw-transform/src/lib.rs
Fixes a few of the issues listed in https://github.com/ActivityWatch/aw-server-rust/issues/66
Depends on https://github.com/ActivityWatch/aw-webui/pull/168
> Fix support for everything in the default query in the web-uis "Query Editor"

- aw-query/src/datatype.rs
- aw-query/src/functions.rs
- aw-query/src/interpret.rs
- aw-query/src/lexer.rs
- aw-query/src/lib.rs
- aw-query/src/parser.rs
Removes quite a few clones as well, some queries might become significantly faster now
> aw-query: Fix clippy issues

- Cargo.lock
- aw-client-rust/tests/test.rs
- aw-server/Cargo.toml
- aw-server/src/android/mod.rs
- aw-server/src/config.rs
- aw-server/src/endpoints/mod.rs
- aw-server/src/logging.rs
- aw-server/src/main.rs
- aw-server/tests/api.rs
- aw-sync/src/main.rs
> Add cli option parsing, --testing and refactoring

- aw-datastore/src/worker.rs
- aw-datastore/tests/datastore.rs
Might fix #95 
Also added a guarantee that DB is commited every 15s.
> Misc datastore improvements

- Cargo.lock
- aw-datastore/src/datastore.rs
- aw-datastore/src/legacy_import.rs
- aw-models/examples/schema.rs
- aw-models/src/bucket.rs
- aw-models/src/export.rs
- aw-models/src/lib.rs
- aw-models/src/tryvec.rs
- aw-server/src/endpoints/bucket.rs
- aw-server/src/endpoints/export.rs
- aw-server/tests/api.rs
> fix: Drop single events if corrupted instead of failing whole import

- .github/workflows/build.yml
@johan-bjareholt Feel free to merge when acknowledged.
> ci: disable fail-fast (workaround for #180)

- Cargo.lock
All the small dependabot PRs (#194 #195 #196 #197 #198 #199 #200 #201) in a single commit.
> build(deps): updated dependencies

- .github/workflows/build.yml
- Makefile
- aw-server/Cargo.toml
- compile-android.sh
- install-ndk.sh
fixes https://github.com/ActivityWatch/aw-server-rust/issues/211
> fix: attempt to fix building for Android

- aw-client-rust/src/lib.rs
- aw-client-rust/tests/test.rs
- aw-server/src/main.rs
- aw-sync/src/sync.rs
> feat: added query parameters to aw-client-rust's get_events

- aw-query/src/functions.rs
- aw-transform/src/filter_keyvals.rs
- aw-transform/src/lib.rs
Another transform that was available in aw-core but not in aw-server-rust.
> feat: added exclude_keyvals transform

- aw-models/src/event.rs
- aw-models/src/timeinterval.rs
- aw-query/src/functions.rs
- aw-transform/src/lib.rs
- aw-transform/src/union_no_overlap.rs
Needed for https://github.com/ActivityWatch/aw-webui/pull/349
aw-core version: https://github.com/ActivityWatch/aw-core/blob/master/aw_transform/union_no_overlap.py
> feat: implement union_no_overlap transform

- aw-transform/src/heartbeat.rs
this the exact scenario which is used on the new swift-based macos window watcher
> chore(test): adding explicit test for long pulse merge

- aw-datastore/src/datastore.rs
- aw-server/src/logging.rs
- aw-server/src/main.rs
- aw-transform/src/heartbeat.rs
- Pull log level from LOG_LEVEL env var
- Log when assets cannot be found
> Source log level from ENV

- aw-server/src/android/mod.rs
- compile-android.sh
- install-ndk.sh
Trying to fix building for Android.
Related: 
- https://github.com/rust-lang/rust/pull/85806
- https://github.com/rust-lang/cc-rs/issues/636
> build: updated Android NDK from r21 to r25b

- aw-transform/src/filter_keyvals.rs
> fix: Remove unwraps from filter_keyvals_regex

- Makefile
changed PREFIX to default to `$XDG_DATA_HOME` unless run with sudo
> updated prefix to standard user-writeable location

- .github/workflows/build.yml
- aw-client-rust/tests/test.rs
- aw-datastore/src/worker.rs
- aw-server/src/logging.rs
- aw-server/src/main.rs
- aw-sync/src/main.rs
- aw-sync/src/sync.rs
- aw-sync/test-server.sh
- aw-sync/test-sync-pull.sh
> feat: allow specifying exactly which db file to sync with

- aw-server/src/dirs.rs
- aw-server/src/main.rs
See https://github.com/ActivityWatch/aw-tauri
> Working on integrating with Tauri

- aw-server/src/endpoints/bucket.rs
used to create buckets with server-local hostname and device_id
aw-server-python impl: https://github.com/ActivityWatch/aw-server/pull/140
> feat: added special hostname `!local`
