- src/endpoints/bucket.rs
As per the [Rocket docs](https://rocket.rs/guide/requests/#format):
>When a route indicates a non-payload-supporting method (HEAD, OPTIONS, and, these purposes, GET) the format route parameter instructs Rocket to check against the Accept header of the incoming request. Only requests where the preferred media type in the Accept header matches the format parameter will match to the route.
Fixes #5
> Removed Accept-based routing requirements for GET routes

- src/transform/mod.rs
- tests/transform.rs
> transform: Fix calculation of gap in flood

- src/android/mod.rs
- src/datastore/datastore.rs
- src/endpoints/bucket.rs
- src/endpoints/import.rs
- src/endpoints/mod.rs
- src/endpoints/query.rs
- src/main.rs
- tests/api.rs
Makes it possible to clone the Datastore producer object.
This will make it possible for the android code to both have the Web API running at the same time as we do other requests to the datastore. Will also probably make it easier to implement sync later on as that would probably run in its own thread and also need access to the datastore.
An example would be:
```
let datastore = datastore::Datastore::new_in_memory();
let state = endpoints::ServerState {
datastore: Mutex::new(datastore.clone()),
asset_path: PathBuf::from("aw-webui/dist"),
};
endpoints::rocket(state, None)
// Do other stuff with the original datastore object
```
> Externalize datastore lock

- Cargo.lock
- Cargo.toml
- src/datastore/datastore.rs
This should make the datastore worker thread continue running even if some really odd things occurs such as corrupt events etc. as all unwraps/expects are replaced with returning a DatastoreError::InternalError instead.
> Upgraded rusqlite and removed unwraps/expect in datastore

- src/datastore/datastore.rs
- src/models/bucket.rs
- tests/datastore.rs
- tests/models.rs
- tests/query.rs
Database migration is pretty simple when using "ALTER TABLE"
> datastore: Add 'data' field to buckets table

- src/datastore/datastore.rs
- src/models/bucket.rs
- src/models/mod.rs
- tests/api.rs
- tests/datastore.rs
- tests/models.rs
- tests/query.rs
- tests/transform.rs
Solves #32 
The resulting data looks like this when doing a request over REST:
```
"metadata": {
"first_starttime": "2018-01-01"
"last_endtime": "2018-01-02"
}
```
If the bucket is empty:
```
"metadata": {
"first_starttime": null
"last_endtime": null
}
```
> datastore: Added bucket metadata and removed external ReplaceLast API

- .cargo/config
- .travis.yml
- compile-android.sh
First step towards fixing https://github.com/ActivityWatch/aw-android/issues/20
> Added x86_64 build target on android

- src/android/mod.rs
- src/datastore/datastore.rs
- src/endpoints/bucket.rs
- tests/api.rs
aw-client-js expects to get a event body as a response when the request is 200 OK, aw-server-rust now responds with the same data as aw-server-python
> Make heartbeat requests respond with a merged heartbeat

- .travis.yml
- Cargo.lock
- README.md
- src/datastore/datastore.rs
- src/lib.rs
- src/macros.rs
- src/main.rs
- src/models/bucket.rs
- src/models/event.rs
- src/models/timeinterval.rs
- src/query/functions.rs
- src/query/mod.rs
- src/transform/mod.rs
- tests/datastore.rs
- tests/macros.rs
- tests/models.rs
- tests/query.rs
- tests/transform.rs
Additions:
- Boolean support
- Basic if/elif/else support
- == support
- Added concat function
- Added contains function
- Better error messages (line numbers during lexing, but not parsing)
- Event and Bucket models now use serde_json Map instead of Value as it should
- Coverage in travis with codecov.io
Issues:
- Since this is the first PR with coverage we will miss coverage report for the base branch so that will always fail
Fixes #44 
Fixes #39
> Query improvements

- Cargo.lock
- Cargo.toml
- src/datastore/datastore.rs
- src/endpoints/bucket.rs
- src/models/event.rs
- tests/api.rs
- tests/datastore.rs
- Sets the default duration to 0 if not specified
- Makes it possible to replace events
- insert_events now returns the events with an assigned id
> datastore: Make it possible to replace events

- src/datastore/datastore.rs
- src/models/bucket.rs
Fixes https://github.com/ActivityWatch/aw-server-rust/issues/23
> datastore: Don't copy buckets events into bucket_cache during import

- src/datastore/datastore.rs
- src/datastore/mod.rs
- src/datastore/worker.rs
- Split worker code out into a seperate module
- instance should now be easy to use without the worker
- Moved commit and uncommited_events out of DatastoreInstance
> datastore: refactoring of relationship between worker and instance

- Cargo.lock
- Cargo.toml
- src/endpoints/mod.rs
This is needed for syncing.
Equivalent PR in aw-server: https://github.com/ActivityWatch/aw-server/pull/61
> Added device_id and exposed it through /api/0/info

- aw-query/tests/query.rs
Previously it always returned true, I had to rewrite it as a macro for it to work properly
> aw-query: Fix false positive assert_err_type function

- aw-datastore/src/datastore.rs
- aw-datastore/src/lib.rs
- aw-datastore/src/worker.rs
- aw-models/src/key_value.rs
- aw-models/src/lib.rs
- aw-server/src/endpoints/key_value.rs
- aw-server/src/endpoints/mod.rs
- aw-server/src/endpoints/settings.rs
- aw-server/tests/api.rs
This PR adds key/value storage functionality. Currently implementing changes based on review feedback.
new features coming into this PR:
Open questions:
> Add key value store

- aw-server/src/config.rs
- aw-server/src/endpoints/cors.rs
Adds reading CORS entries from config and writing default CORS entry to config as comment like other config options on first start without config.
> Add CORS support to config and default config

- Makefile
Helps us avoid building aw-server-rust twice in CI (first in release mode, and then in debug mode when tests are run).
> added RELEASE option to Makefile (for faster non-release builds)

- aw-server/src/config.rs
- aw-server/src/dirs.rs
- aw-server/src/endpoints/mod.rs
- aw-server/src/logging.rs
I know this will leave ANSI color escape sequences in the logfiles, but dumb to repeat the entire formatting, and if its a big issue there are better ways to do it (but I got tired of looking at fern docs to figure out the way).
> reduced logging and simplified logging pipeline

- .github/workflows/build.yml
- Makefile
- todo.md
> Use grcov instead of kcov

- .github/workflows/build.yml
- Change ubuntu-18.04 with ubuntu-latest (so once ubuntu-latest becomes 20.04 we don't have to do anything)
- Force new build cache for Linux to fix broken builds from the previos grcov PR #123
> Misc CI improvements

- aw-server/Cargo.toml
See: https://users.rust-lang.org/t/rust-on-android-today/17884/14?u=erikbjare
> build: added vendored openssl-sys dependency on Android

- aw-server/src/android/mod.rs
Needed for https://github.com/ActivityWatch/aw-android/issues/41
> fix: added limit parameter to the JNI wrapper for get_events

- aw-transform/src/chunk.rs
- aw-transform/src/filter_keyvals.rs
- aw-transform/src/flood.rs
> fix: If events merge during flood, choose the longest endtime

- Cargo.lock
- aw-server/Cargo.toml
- aw-server/src/main.rs
Important because otherwise malloc is very slow at releasing memory back
to the kernel, making the RAM usage grow endlessly when doing large
queries.
> fix: Set allocator to jemalloc

- Cargo.lock
- aw-models/src/key_value.rs
- aw-server/src/endpoints/settings.rs
- aw-server/tests/api.rs
Before it was forced to be a string
We should probably discuss this a little further before merging. @ErikBjare and @xylix, what do you think?
Pros:
- Client can send any JSON type and not only string, doesn't have to manually deserialize json within the string if it wants to use some other type than string
Cons:
- The datastore now contains serialized JSON rather than just a string
Fixes #178
> Make settings value possibly any json type

- aw-server/src/main.rs
Needed for https://github.com/ActivityWatch/activitywatch/pull/506
> fix: correct lookup of asset_path for .app bundles on macOS

- aw-server/src/dirs.rs
appdirs does this right.
Behaves the same as before on UNIX: https://docs.rs/appdirs/0.2.0/src/appdirs/lib.rs.html#139-145
Behaves correctly on macOS: https://docs.rs/appdirs/0.2.0/src/appdirs/lib.rs.html#58-61
> fix: corrected non-standard log dir on macOS (fixes #187)

- .github/workflows/build.yml
- .gitignore
- Makefile
Largely based on how grcov themselves do it: https://github.com/mozilla/grcov/blob/master/.travis.yml
From https://github.com/mozilla/grcov/commit/e98d5ddc6570a9f4b6d113b6931fec53357c064b, it seems we can go even further and remove `CARGO_INCREMENTAL` and `RUSTDOCFLAGS`.
Hopefully helps with #189 
Screenshot of HTML report when I run locally. Note that ~~source-based coverage~~ grcov doesn't support branch coverage (I asked them about it in https://github.com/mozilla/grcov/issues/520):
> ci: switched to source-based coverage

- .github/workflows/build.yml
> ci: set cache key to include rustc_hash

- aw-server/Cargo.toml
- aw-server/src/main.rs
jemalloc is only properly tested on x86 on Linux and doesn't even compile for aarch64 it seems.
Needed for aw-server to compile for Linux phones such as PinePhone and Librem 5.
> aw-server: Disable jemalloc on non-x86 CPUs

- aw-datastore/src/legacy_import.rs
Since the "author" field was not passed to appdirs, the old aw-server folder was not correctly set for the old aw-server database and therefore skipped.
> aw-datastore: Fix broken legacy import on Windows

- aw-datastore/src/datastore.rs
- aw-datastore/tests/datastore.rs
Initially thought this was broken, but it wasn't (only for `get_eventcount`). Added a test for it anyway.
> test: added tests for datastore query of events that cover the queried range

- Cargo.lock
- README.md
- aw-client-rust/src/lib.rs
- aw-server/Cargo.toml
- aw-server/src/main.rs
- aw-sync/Cargo.toml
- aw-sync/README.md
- aw-sync/src/lib.rs
- aw-sync/src/main.rs
- aw-sync/src/sync.rs
- aw-sync/tests/sync.rs
Resuming work from #71 
What's missing:
- Partially done, but can probably be done better.
> Sync stuff

- aw-query/src/functions.rs
- aw-query/tests/query.rs
- aw-transform/src/find_bucket.rs
This functionality was available in aw-core. 
Needed for new queries which don't assume a certain bucket ID containing the hostname.
Also needed for my PR in https://github.com/ErikBjare/quantifiedme/pull/4
> feat: added hostname filtering support to find_bucket

- aw-transform/src/flood.rs
Changes the behavior of aw-server-rust flooding to work the same as flooding in aw-core.
Part of the issue is described here: https://github.com/ActivityWatch/activitywatch/issues/602#issuecomment-970240728
- Better tests
- ~~Forward flooding instead of meet-in-middle (aw-core uses flood-from-longest though)~~
- Tbh I'm not sure what is best, but forward flooding feels like it introduces *some* duration-bias towards later events, which seems unfair.
- Flood-from-longest will lead to the lowest relative error, I guess, and they have some sort of higher probability to occur anyway.
- More tests (goal: ~100% coverage for `flood.rs`)
> fix: improving flooding

- .github/workflows/build.yml
- .github/workflows/lint.yml
As described in https://github.com/ActivityWatch/aw-server-rust/pull/270#issuecomment-1074933764
> ci: switched to tarpaulin for code coverage

- aw-server/src/main.rs
feat: Add cmdline arg which can override asset path
feat: fallback to `/usr/local/share:/usr/share` when `XDG_DATA_DIRS` is not set or empty
References:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
> add cmdline arg and change the `XDG_DATA_DIRS`

- .gitignore
- aw-client-rust/src/lib.rs
- aw-client-rust/tests/test.rs
- aw-datastore/src/datastore.rs
- aw-datastore/src/lib.rs
- aw-datastore/src/worker.rs
- aw-server/src/main.rs
- aw-sync/Cargo.toml
- aw-sync/README.md
- aw-sync/src/accessmethod.rs
- aw-sync/src/lib.rs
- aw-sync/src/main.rs
- aw-sync/src/sync.rs
- aw-sync/test-import-sync.sh
- aw-sync/test-server.sh
- aw-sync/test-sync.sh
- aw-sync/tests/sync.rs
- Able to set: sync folder, pick buckets, since some date, which instance to connect to as the local one (incl `--testing`), and which mode (pull, push, both).
- See the added `test-*.sh` scripts
> another sync PR

- aw-server/src/config.rs
- aw-server/src/logging.rs
- aw-server/src/main.rs
- Dont filter out Rocket messages when in Debug or Trace log level
- also fixes inverted testing condition when config
Eg logs. - https://github.com/ActivityWatch/aw-webui/actions/runs/3341509927/jobs/5532792619#step:15:16
> Extra debug logging when in testing mode

- aw-server/src/logging.rs
its better to be more verbose if its LogLevel >= Debug, hence no need to filter out any messages from modules if LogLevel >= Debug
> fix: only filter when not in debug mode

- aw-server/src/config.rs
- aw-server/src/endpoints/mod.rs
- aw-server/src/main.rs
I struggled a bit with this since it is my first time with Rust but here it is. I used the FileServer from Rocket because that is the easiest way I found to get custom HTML per watcher.
How to use:
Create a `visualizations` folder in your [data](https://docs.activitywatch.net/en/latest/directories.html#data) folder. Then create a folder for your custom watcher and put your index.html here. Example: `/home/USER/.local/share/activitywatch/aw-server-rust/visualizations/aw-watcher-test/index.html`
You can also load JavaScript from other files, just put them in the same directory.
I tested it with my custom watcher and it works with [custom visualization support](https://github.com/ActivityWatch/aw-server/pull/83) of aw-server web-ui (and so aw-server-rust).
> feat: add custom visualization support (custom_static)

- compile-android.sh
- install-ndk.sh
We briefly had working builds for r25 (https://github.com/ActivityWatch/aw-server-rust/commit/6f1d5b2242ddc7c9cd17580ae4c556a8c210ca55), but they started failing with a weird:
```
= note: ld: error: unable to find library -lgcc
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```
This change works locally for me (on macOS), hoping it fixes CI too.
> build: downgrade NDK to r21e and added macOS Android build support

- aw-server/Cargo.toml
- aw-server/src/android/mod.rs
- the previous android fix to rocket update was not functional #255
- previous version rocket was async, newer version needs to be awaited
- reaf'ed code a little
> fix: several android fixes

- .github/workflows/build.yml
Due to "Couldn't find a release tarball containing binaries for latest".
Probably due to release artifacts/tarballs changing their naming, making the action unable to find the tarball.
> ci: pinned tarpaulin version

- Cargo.lock
- aw-server/Cargo.toml
- aw-server/src/logging.rs
- panic log from various sites is written to `stderr` by default and due to https://github.com/ActivityWatch/aw-server/issues/27#issue-233126783 its not redirected/piped to `logfile`
eg. log.
```shell
[2023-04-08 19:43:13][[33mWARN[0m][aw_transform::flood]: Gap was of negative duration and could NOT be safely merged (-PT397.291Ss). This warning will only show once per batch.
[2023-04-08 19:43:13][[31mERROR[0m][panic]: thread 'rocket-worker-thread' panicked at 'meow': aw-transform\src\period_union.rs:49
0: backtrace::backtrace::trace
1: backtrace::capture::Backtrace::new
2: <backtrace::capture::Backtrace as core::default::Default>::default
3: log_panics::Config::install_panic_hook
4: alloc::boxed::impl$47::call
at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library\alloc\src\boxed.r …
```
> debug: redirect stderr panic log to rust logger

- Cargo.lock
- aw-client-rust/Cargo.toml
- aw-client-rust/src/blocking.rs
- aw-client-rust/src/lib.rs
- aw-client-rust/tests/test.rs
- aw-sync/src/accessmethod.rs
- aw-sync/src/main.rs
- aw-sync/src/sync.rs
The problem is not only that the current functionality is less useful in async context. The client cannot be used in async context at all as is:
https://docs.rs/reqwest/latest/reqwest/blocking/
> Conversely, the functionality in reqwest::blocking must not be executed within an async runtime, or it will panic when attempting to block
I've used tokio's runtime to block because reqwest uses tokio blocking internally as well.
https://github.com/seanmonstar/reqwest/blob/master/src/blocking/wait.rs
It also uses a current thread runtime, but with timeouts. However, the async client specified the timeout already, so it shouldn't matter much.
> Split client to async and blocking

- aw-server/build.rs
Otherwise, `../aw-webui/dist` is always created which contradicts the flexibility from the env variable. Also, if `AW_WEBUI_DIR` is already and explicitly set then it supposedly means that the build runner has taken care of the matter.
Follow up on https://github.com/ActivityWatch/aw-server-rust/pull/385
> fix: improve AW_WEBUI_DIR handling

- .github/workflows/build.yml
- Cargo.lock
- aw-query/Cargo.toml
- aw-query/benches/benchmark.rs
- aw-server/src/lib.rs
- aw-transform/Cargo.toml
- aw-transform/benches/bench.rs
Fixes #278
- use `dtolnay/rust-toolchain` to setup rust since original action is not maintained
- use the latest commit of `plex` to support stable rust
- use `criterion` to run benchmarks since built-in bench is unstable
> build: use stable rust, and criterion.rs for benching

- Cargo.lock
- aw-server/src/dirs.rs
- aw-server/src/logging.rs
- aw-server/src/main.rs
- aw-sync/Cargo.toml
- aw-sync/src/dirs.rs
- aw-sync/src/lib.rs
- aw-sync/src/main.rs
- aw-sync/src/sync.rs
- aw-sync/src/sync_wrapper.rs
- aw-sync/src/util.rs
- aw-sync/test-sync-pull.sh
- aw-sync/test-sync-push.sh
> feat(sync): moved logic in sync-test scripts into rust, enabling sync with a single command

- aw-query/src/functions.rs
- aw-transform/benches/bench.rs
- aw-transform/src/filter_period.rs
In general, this reduces complexity of O(n^2) to O(n lgn).
From the benchmark we can see the performance gain:
```bash
Running benches/bench.rs (target/release/deps/bench-a5f1a4e304f6ce84)
Gnuplot not found, using plotters backend
1000 events             time:   [443.46 µs 444.09 µs 444.76 µs]
change: [-92.832% -92.611% -92.413%] (p = 0.00 < 0.05)
Performance has improved.
```
> perf: improve performance of filter_period_intersect

- aw-client-rust/src/blocking.rs
- aw-client-rust/src/lib.rs
- aw-client-rust/tests/test.rs
- aw-models/src/bucket.rs
- aw-sync/src/dirs.rs
- aw-sync/src/main.rs
- aw-sync/src/sync.rs
- aw-sync/src/sync_wrapper.rs
- aw-sync/src/util.rs
1. I tried to remove as many unwraps(), panics()!, etc, with Result<>.  I did not go deep into the core sync logic, as I'm not as comfortable there.
2. I move a bunch of the parsing out of the main function and into arg-specific functions.  That way, clap can provide all the context needed for an invalid argument.  I also replaced "String" with more specific types in the clap commands.
AwClient was the most "substantial" change here.  It's new function had several points where it would panic out.  Therefore, I replaced its constructor arguments with types that prevented these panics.
Instead of taking a host+port, it just takes a reqwest::Url.  This prevents the panic if the url is malformed.  Additionally, it would try to read the hostname() which would also panic if the hostname used …
> Replace panics with results & better option types
